#Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

##SOCKET directory - /dev/socket
#Create folder for gptp where socket will be stored
d /dev/socket/gptp 0755 vnw vnw - -
